version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/NDLytics
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_docker.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/install_aws_cli.sh
      timeout: 300
      runas: root
    - location: scripts/setup_iam_role.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/setup_ssl.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_docker.sh
      timeout: 60
