application_lists = {
    "permission_list": [
        "dashboard",
        "campaigns",
        "filemanager",
        "settings",
        "tickets",
        "requests",
        "myapps",
        "apps",
    ],
    "role_list": [
        "_role_system_admin",
        "_role_company_admin",
        "_role_company_user",
    ],
    "settings_page_menu_list": [
        {
            "grid_item_name": "My Profile",
            "grid_item_description": "Manage your profile",
            "grid_item_icon": "o_person",
            "grid_item_path": "/settings/my-profile",
        },
        {
            "grid_item_name": "Manage Users",
            "grid_item_description": "Manage users and permissions",
            "grid_item_icon": "o_people",
            "grid_item_path": "/settings/manage-users",
        },
        {
            "grid_item_name": "Ticket System",
            "grid_item_description": "Manage ticket system settings",
            "grid_item_icon": "s_confirmation_number",
            "grid_item_path": "/settings/ticket-system",
        },
    ],
    "app_list": [
        {
            "title": "Dashboard",
            "icon": "dashboard",
            "color": "rgba(255,255,255,1)",
            "route": "/dashboard",
            "permissions": ["dashboard_view"],
        },
        {
            "title": "Campaigns",
            "icon": "dialpad",
            "color": "rgba(255,255,255,1)",
            "route": "/campaigns",
            "permissions": ["dashboard_view"],
        },
        {
            "title": "Tasks",
            "icon": "fact_check",
            "color": "rgba(255,255,255,1)",
            "route": "/tasks",
            "permissions": ["dashboard_view"],
        },
        {
            "title": "Goals",
            "icon": "flag",
            "color": "rgba(255,255,255,1)",
            "route": "/goals",
            "permissions": ["dashboard_view"],
        },
        {
            "title": "Settings",
            "icon": "settings",
            "color": "rgba(255,255,255,1)",
            "route": "/settings",
            "permissions": ["settings_view"],
        },
    ],
    "client_map": {
        "2": "New Day Fund",
        "400023": "Request Fund",
        "400041": "Bequest Fund",
        "300005": "Davis & Beyer",
        "400025": "DBS Consult",
        "400016": "Demo, Johnny",
        "300004": "Dental Excel",
        "300002": "Farah Dental",
        "400001": "MacDonald",
        "400008": "Kaufman Thomas",
        "400006": "Lakeview Auto",
        "400011": "Mapp Realty",
        "400027": "MN03132022",
        "400014": "Palmetto Dental",
        "400038": "Praters Plumbing",
        "400005": "Raven Dental",
        "400040": "Seaboard Marine",
        "400010": "Service One",
        "400031": "SpeedwayDSM",
        "400003": "SPLASH2006",
        "400013": "Sancentrix Bio",
        "400012": "XL Funding LLC",
        "400045": "Fintap",
        "400046": "ICare",
    },
    "operator_list": {
        "2115221": "MPP",
        "2133845": "ARC",
        "2156762": "CMO",
        "2144867": "CJE",
    },
}
