page_routes_list = [
    {
        "page_name": "Dashboard",
        "route": "/dashboard",
        "icon": "dashboard",
        "root_route": "/",
        "required_permissions": ["dashboard_view"],
    },
    {
        "page_name": "Campaigns",
        "route": "/campaigns",
        "icon": "campaign",
        "root_route": "/",
        "required_permissions": ["campaigns_view"],
    },
    {
        "page_name": "File Manager",
        "route": "/file-manager",
        "icon": "file_present",
        "root_route": "/",
        "required_permissions": ["filemanager_view"],
    },
    {
        "page_name": "Tickets",
        "route": "/tickets",
        "icon": "s_confirmation_number",
        "root_route": "/",
        "required_permissions": ["tickets_view"],
    },
    {
        "page_name": "Requests",
        "route": "/requests",
        "icon": "s_all_inbox",
        "root_route": "/",
        "required_permissions": ["requests_view"],
    },
    {
        "page_name": "My Apps",
        "route": "/my-apps",
        "icon": "apps",
        "root_route": "/",
        "required_permissions": ["myapps_view"],
    },
    {
        "page_name": "Models",
        "route": "/models",
        "icon": "o_model",
        "root_route": "/",
        "required_permissions": ["models_view"],
    },
    {
        "page_name": "Settings",
        "route": "/settings",
        "icon": "settings",
        "root_route": "/",
        "required_permissions": ["settings_view"],
    },
    {
        "page_name": "Development",
        "route": "/development",
        "icon": "settings",
        "root_route": "/",
        "required_permissions": ["dashboard_view"],
    },
]
